---
title: "Descriptive analysis of missing visual data"
author: "Silvia Téliz"
date: "2025-04-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = F, message = F)
```

```{r packages}
library(tidyverse)
library(magrittr)
```

```{r data}
candidates <- read_csv("data/candidates.csv")
```

# General descriptive analysis
```{r general}
# Count gender by party
candidates %>% 
  group_by(party) %>% 
  summarise(m = sum(sex=="m"),
            f = sum(sex=="f")) %>%
  arrange(desc(f))

# Count incumbency by party
candidates %>% 
  group_by(party) %>% 
  summarise(n_incumbents = sum(incumbency=="1")) %>%
  arrange(desc(n_incumbents))
```



# Descriptive analysis of missing data in usage of visual platforms

```{r visual_platform}
# Obtain percentage of candidates that published each visual platform

# General count
candidates %>% 
  summarise(
    portrait = round(sum(portrait_d == 1) / n(), 2),
    webpage = round(sum(webpage_d == 1) / n(), 2),
    facebook = round(sum(!is.na(facebook)) / n(), 2),
    twitter = round(sum(!is.na(twitter)) / n(), 2),
    instagram = round(sum(!is.na(instagram)) / n(), 2),
    youtube = round(sum(!is.na(youtube)) / n(), 2)
  ) %>% 
  arrange(desc(portrait))

# Count per party
candidates %>% 
  group_by(party) %>% 
  summarise(
    portrait = round(sum(portrait_d == 1) / n(), 2),
    webpage = round(sum(webpage_d == 1) / n(), 2),
    facebook = round(sum(!is.na(facebook)) / n(), 2),
    twitter = round(sum(!is.na(twitter)) / n(), 2),
    instagram = round(sum(!is.na(instagram)) / n(), 2),
    youtube = round(sum(!is.na(youtube)) / n(), 2)
  ) %>% 
  arrange(desc(portrait))

# Count per position
candidates %>% 
  group_by(position) %>% 
  summarise(
    portrait = round(sum(portrait_d == 1) / n(), 2),
    webpage = round(sum(webpage_d == 1) / n(), 2),
    facebook = round(sum(!is.na(facebook)) / n(), 2),
    twitter = round(sum(!is.na(twitter)) / n(), 2),
    instagram = round(sum(!is.na(instagram)) / n(), 2),
    youtube = round(sum(!is.na(youtube)) / n(), 2)
  ) %>% 
  arrange(desc(portrait))

# Count per state
candidates %>% 
  filter(position == "dep") %>%
  group_by(state) %>% 
  summarise(
    portrait = round(sum(portrait_d == 1) / n(), 2),
    webpage = round(sum(webpage_d == 1) / n(), 2),
    facebook = round(sum(!is.na(facebook)) / n(), 2),
    twitter = round(sum(!is.na(twitter)) / n(), 2),
    instagram = round(sum(!is.na(instagram)) / n(), 2),
    youtube = round(sum(!is.na(youtube)) / n(), 2)
  ) %>% 
  arrange(desc(portrait))

candidates %>% 
  filter(position == "sen") %>%
  group_by(state) %>% 
  summarise(
    portrait = round(sum(portrait_d == 1) / n(), 2),
    webpage = round(sum(webpage_d == 1) / n(), 2),
    facebook = round(sum(!is.na(facebook)) / n(), 2),
    twitter = round(sum(!is.na(twitter)) / n(), 2),
    instagram = round(sum(!is.na(instagram)) / n(), 2),
    youtube = round(sum(!is.na(youtube)) / n(), 2)
  ) %>% 
  arrange(desc(portrait))

candidates %>% 
  filter(position == "pres") %>%
  group_by(party) %>% 
  summarise(
    portrait = round(sum(portrait_d == 1) / n(), 2),
    webpage = round(sum(webpage_d == 1) / n(), 2),
    facebook = round(sum(!is.na(facebook)) / n(), 2),
    twitter = round(sum(!is.na(twitter)) / n(), 2),
    instagram = round(sum(!is.na(instagram)) / n(), 2),
    youtube = round(sum(!is.na(youtube)) / n(), 2)
  ) %>% 
  arrange(desc(portrait))

```

# Map missing data








