---
title: "Descriptive analysis"
author: "Silvia Téliz"
date: "2025-05-13"
output: html_document
---

This script matches the skin tone data with the candidate results data. The skin tone data is obtained from the `skintone` dataset, which contains the skin tone labels for candidates' portraits. The candidate results data is obtained from the `dep_cand_results`, `sen_cand_results`, and `pres_cand_results` datasets.

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(tidyverse)
library(magrittr)
```

# Import data

```{r data}
# Candidate-results data
dep_cand_results <- read_csv("../data/processed/03_dep_cand_results.csv")
pres_cand_results <- read_csv("../data/processed/03_pres_cand_results.csv")
sen_cand_results <- read_csv("../data/processed/03_sen_cand_results.csv")

# Skin tone measurement data
skintone <- read_csv("../data/processed/04_skintone.csv")
```

# General wrangling

```{r clean_skintone}
# Select relevant variables from skintone data. In some images, two faces were detected. We select the one with the highest confidence score.

skintone_ine <- skintone %>%
  filter(source == "ine" & face_id == 1) %>%
  select(file, tone_label, skin_tone)
names(skintone_ine) <- c("id", "skin_ine", "hex_ine")


skintone_sv <- skintone %>%
  filter(source == "sv" & face_id == 1) %>%
  select(file, tone_label, skin_tone)
names(skintone_sv) <- c("id", "skin_sv", "hex_sv")

# Remove .jpg extension from id column
skintone_ine <- skintone_ine %>%
  mutate(id = str_remove(id, ".jpg"))
skintone_sv <- skintone_sv %>%
  mutate(id = str_remove(id, ".jpg"))

```


```{r match}
# Match skin tone data with candidate results

# Deputies dataset
dep_cand_results <- dep_cand_results %>%
  left_join(skintone_ine, by = "id") %>%
  left_join(skintone_sv, by = "id") %>%
  mutate(contest = "dep")

# Senators dataset
sen_cand_results <- sen_cand_results %>%
  left_join(skintone_ine, by = "id") %>%
  left_join(skintone_sv, by = "id") %>%
  mutate(contest = "sen")

# President dataset
pres_cand_results <- pres_cand_results %>%
  left_join(skintone_ine, by = "id") %>%
  left_join(skintone_sv, by = "id") %>%
  mutate(contest = "pres")

```

```{r join}
# Join all datasets
cand_skin_results <- bind_rows(dep_cand_results, sen_cand_results, pres_cand_results)

```


# Export dataset

```{r export}
# Export the dataset
write_csv(cand_skin_results, "../data/processed/05_cand_skin_results.csv")

```



